/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package review;

import controller.ProcessingCtrl;
import controller.UICtrl;
import controller.UICtrlV2;
import java.util.UUID;
import javax.swing.JFileChooser;

/**
 *
 * @author nsl
 */
public class NoPlPanelV2 extends javax.swing.JPanel {

	/**
	 * Creates new form NoPlPanelV2
	 */
	public NoPlPanelV2() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();

                jLabel1.setText("No Gallery found.");

                jButton1.setText("Add a new gallery !");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel1))
                                        .addComponent(jButton1))
                                .addContainerGap(126, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addContainerGap(142, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		JFileChooser jfc = new JFileChooser();
		jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		jfc.setMultiSelectionEnabled(false);
		if(jfc.showOpenDialog(this.jButton1) == JFileChooser.APPROVE_OPTION){
			UUID uid = ProcessingCtrl.
				acknowledge(jfc.getSelectedFile());
			UICtrlV2.closeNoPl();
			UICtrlV2.buildLabels(UICtrlV2.loadedPhotoLists.get(uid));
			UICtrlV2.setCurrent(uid);
			UICtrlV2.gui.repaint();
			System.out.println("HELLO REPAINT");
			/*
			UICtrl.labels.put(uid, UICtrl.getlabels(ProcessingCtrl.loadedPhotoLists.get(uid)));
			UICtrl.setCurrent(uid);
			UICtrl.pll.add(UICtrl.getCurrent());
			*/
			
				}
        }//GEN-LAST:event_jButton1ActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        // End of variables declaration//GEN-END:variables
}
