/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.UICtrlV2;
import model.ImgModel;
import model.PhotoList;

/**
 *
 * @author nsl
 */
public class DataPanelV2 extends javax.swing.JPanel {

	UICtrlV2 uictrl = new UICtrlV2();
	private int imgCount = 0;
	private int analysedCount = 0;
	private int failCount = 0;
	private int successCount = 0;

	/**
	 * Creates new form DataPanelV2
	 */
	public DataPanelV2() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel1 = new javax.swing.JPanel();
                path = new javax.swing.JLabel();
                result = new javax.swing.JLabel();
                exif = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                picAnalysed = new javax.swing.JLabel();
                sucess = new javax.swing.JLabel();
                fails = new javax.swing.JLabel();

                path.setText("Path : ");

                result.setText("Bib numbers :");

                exif.setText("EXIF data :");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(path)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(result)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(exif)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6)))
                                .addContainerGap(453, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(path)
                                        .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(result)
                                        .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(exif)
                                        .addComponent(jLabel6))
                                .addContainerGap(72, Short.MAX_VALUE))
                );

                jLabel4.getAccessibleContext().setAccessibleName("lPath");
                jLabel5.getAccessibleContext().setAccessibleName("lResult");
                jLabel6.getAccessibleContext().setAccessibleName("lExif");

                jTabbedPane1.addTab("Picture Data", jPanel1);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 580, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 187, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Analyze", jPanel2);

                picAnalysed.setText("Pictures analyzed :");

                sucess.setText("Success :");

                fails.setText("Fails :");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(picAnalysed)
                                        .addComponent(sucess)
                                        .addComponent(fails))
                                .addContainerGap(432, Short.MAX_VALUE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(picAnalysed)
                                .addGap(18, 18, 18)
                                .addComponent(sucess)
                                .addGap(18, 18, 18)
                                .addComponent(fails)
                                .addContainerGap(73, Short.MAX_VALUE))
                );

                jTabbedPane1.addTab("Analysis Results", jPanel3);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
                );

                jTabbedPane1.getAccessibleContext().setAccessibleName("Picture Data");
        }// </editor-fold>//GEN-END:initComponents

public DataPanelV2 refreshData(){
		
		PhotoList pl = UICtrlV2.getCurrent();
		this.imgCount = pl.getPhotolist().size();
		this.picAnalysed.setText("Pictures analyzed : " + this.analysedCount + "/" + this.imgCount );
		this.sucess.setText("Success : " + this.successCount);
		this.fails.setText("Fail : "+ this.failCount);
		return this;

	}
	public DataPanelV2 refreshImg() {
		ImgModel im = UICtrlV2.getSelected();
		if (im == null) {
			this.path.setText("Path : ");
			this.result.setText("Bibs : ");
		} else {
			this.path.setText("Path : " + im.getPath());
			this.result.setText((im.getResult().isEmpty()) ? "Bibs : "
				+ "not analyzed" : im.getResult().toString());
			}
		return this;
	}
	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel exif;
        private javax.swing.JLabel fails;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JLabel path;
        private javax.swing.JLabel picAnalysed;
        private javax.swing.JLabel result;
        private javax.swing.JLabel sucess;
        // End of variables declaration//GEN-END:variables
}
