/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.Controller;
import controller.ProcessingCtrl;
import controller.UICtrlV2;
import javax.swing.JOptionPane;

/**
 *
 * @author nsl
 */
public class GUIV2 extends javax.swing.JFrame {

	/**
	 * Creates new form GUIV2
	 */
	public GUIV2() {
		initComponents();
	}

	private GUIV2(String recodossard) {
		super(recodossard);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mainPanelV21 = new GUI.MainPanelV2();
                noPlPanelV21 = new GUI.NoPlPanelV2();
                jMenuBar1 = new javax.swing.JMenuBar();
                jMenu1 = new javax.swing.JMenu();
                jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
                jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
                jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
                jMenu3 = new javax.swing.JMenu();
                jMenuItem1 = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("RecoDossards");

                jMenu1.setText("Settings");

                jCheckBoxMenuItem4.setSelected(true);
                jCheckBoxMenuItem4.setText("Use EXIF Data");
                jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jCheckBoxMenuItem4ActionPerformed(evt);
                        }
                });
                jMenu1.add(jCheckBoxMenuItem4);

                jCheckBoxMenuItem2.setSelected(true);
                jCheckBoxMenuItem2.setText("Enable Debug");
                jMenu1.add(jCheckBoxMenuItem2);

                jCheckBoxMenuItem1.setSelected(true);
                jCheckBoxMenuItem1.setText("Additionnal Data");
                jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jCheckBoxMenuItem1ActionPerformed(evt);
                        }
                });
                jMenu1.add(jCheckBoxMenuItem1);

                jMenuBar1.add(jMenu1);

                jMenu3.setText("About");

                jMenuItem1.setText("About Us");
                jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItem1ActionPerformed(evt);
                        }
                });
                jMenu3.add(jMenuItem1);

                jMenuBar1.add(jMenu3);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(noPlPanelV21, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainPanelV21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mainPanelV21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(noPlPanelV21, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
		JOptionPane.showMessageDialog(null, "RecoDossard v0.9 \n Authors : Alaoui M'Darhri Anas,  Leblond Xavier, Malledant Solène\n ENSIBS INFO 3 2015/2016", "Recodossard v0.9", JOptionPane.INFORMATION_MESSAGE);
		
		
        }//GEN-LAST:event_jMenuItem1ActionPerformed

        private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
                // TODO add your handling code here:
			ProcessingCtrl.setProcessSettings(this.jCheckBoxMenuItem4.getState(), this.jCheckBoxMenuItem1.getState(), this.jCheckBoxMenuItem2.getState());
        }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

        private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUIV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUIV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUIV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUIV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				UICtrlV2.gui = new GUIV2("recodossard");
					UICtrlV2.gui.noPlPanelV21.setVisible(true);
					UICtrlV2.gui.mainPanelV21.setVisible(false);
					UICtrlV2.gui.setVisible(true);
			}
		});
	}

	public MainPanelV2 getMp() { 
		return this.mainPanelV21;
	}
	public NoPlPanelV2 getNplp() { 
		return this.noPlPanelV21;
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
        private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
        private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenu jMenu3;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuItem jMenuItem1;
        private GUI.MainPanelV2 mainPanelV21;
        private GUI.NoPlPanelV2 noPlPanelV21;
        // End of variables declaration//GEN-END:variables

	public void switchPanels() {
		this.getNplp().setVisible(false);
		this.getMp().setVisible(true);
		this.pack();
		this.getContentPane().repaint();
	}
}
