/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.UICtrlV2;
import java.awt.GridLayout;
import java.util.UUID;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author nsl
 */
public class PlPanelV2 extends javax.swing.JPanel {


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JScrollPane getSp()
    {
	    JScrollPane sp = new JScrollPane(this);
	    sp.setVisible(true);
	    sp.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
	    sp.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
	    sp.setBackground(new java.awt.Color(102, 255, 153));
	    sp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
	    return sp;
    }
    // End of variables declaration//GEN-END:variables
	
	/**
	 * Creates new form PlPanelV2
	 */
	public PlPanelV2() {
		initComponents();
		this.setLayout(new GridLayout(0,7));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {


                GridLayout layout = new GridLayout(0,7);
                layout.setVgap(10);
                this.setLayout(layout);


        }// </editor-fold>//GEN-END:initComponents

	public void refresh(UUID pl) {
		//JPanel tmp = new JPanel();
		int i = 0;
		this.removeAll();
		for(JLabel jl : UICtrlV2.labels.get(pl)) {
			// Modifier files par pl surement pour récupérer la photo en elle même (en récupérant le chemin).
			this.add(jl);
			jl.setVisible(true);
			//tmp.add(jl);
			//System.out.println("tmp  " + tmp.getComponents()[i].toString());
			//i++;
		}
		//tmp.setVisible(true);
		this.repaint();
		//this.jScrollPane1.setVisible(true);
		//this.jScrollPane1.revalidate();
		//this.jScrollPane1.repaint();

	}

}
